name: Tag Branch on Push

on:
  push:
    branches:
      - '**'
jobs:
  tag-commit:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches
      
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Tag commit with branch name
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"
          echo "Commit SHA: $GITHUB_SHA"

          # Delete the remote tag if it exists
          git push origin ":refs/tags/$BRANCH_NAME" 2>/dev/null || echo "Remote tag $BRANCH_NAME does not exist, creating new one..."

          # Create new tag at current commit
          git tag -f "$BRANCH_NAME" "$GITHUB_SHA"

          # Push the tag explicitly using refs/tags/
          git push origin "refs/tags/$BRANCH_NAME"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

